# Generated by Django 3.0.7 on 2020-06-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=10)),
                ('real_name', models.CharField(max_length=30)),
                ('tz', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FT_testApp.Members')),
            ],
        ),
    ]
